'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { BarChart3, Check, CircleDollarSign, Clock3, Plus, RotateCcw, Target, Trash2, TrendingUp, WalletCards, X } from 'lucide-react';
import { PerformanceOperation as Operation, PerformanceResult as Result, operationClvPercent } from '@/lib/performanceOperations';
import { formatUnits, readBettingUnitValue, saveBettingUnitValue, stakeToUnits, unitsToStake } from '@/lib/unitSettings';

const STORAGE_KEY = 'ia-cantos-performance-operations-v1';
const BANKROLL_KEY = 'ia-cantos-performance-bankroll-v1';
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const number = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 });

function readOperations(): Operation[] { if (typeof window === 'undefined') return []; try { const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || '[]'); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function profit(operation: Operation) { if (operation.result === 'win') return operation.stake * (operation.odds - 1); if (operation.result === 'loss') return -operation.stake; return 0; }

export default function PerformanceCenterPage() {
  const [operations, setOperations] = useState<Operation[]>([]);
  const [initialBankroll, setInitialBankroll] = useState(1000);
  const [unitValue, setUnitValue] = useState(100);
  const [stakeMode, setStakeMode] = useState<'units' | 'money'>('units');
  const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), match: '', league: '', market: 'Total de escanteios', odds: '1.90', stake: '0.25', result: 'open' as Result });
  const [filter, setFilter] = useState('all');
  const [closingOdds, setClosingOdds] = useState<Record<string, string>>({});

  useEffect(() => { setOperations(readOperations()); setUnitValue(readBettingUnitValue()); const stored = Number(window.localStorage.getItem(BANKROLL_KEY)); if (Number.isFinite(stored) && stored > 0) setInitialBankroll(stored); }, []);
  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(operations)); }, [operations]);
  useEffect(() => { window.localStorage.setItem(BANKROLL_KEY, String(initialBankroll)); }, [initialBankroll]);
  useEffect(() => { saveBettingUnitValue(unitValue); }, [unitValue]);

  function addOperation(event: FormEvent) {
    event.preventDefault();
    const odds = Number(form.odds.replace(',', '.'));
    const enteredStake = Number(form.stake.replace(',', '.'));
    const stake = stakeMode === 'units' ? unitsToStake(enteredStake, unitValue) : enteredStake;
    if (!form.match.trim() || !form.league.trim() || !form.market.trim() || odds <= 1 || stake <= 0) return;
    setOperations((current) => [{ id: crypto.randomUUID(), date: form.date, match: form.match.trim(), league: form.league.trim(), market: form.market.trim(), odds, stake, result: form.result }, ...current]);
    setForm((current) => ({ ...current, match: '', league: '', odds: '1.90', stake: stakeMode === 'units' ? '0.25' : String(unitValue / 4), result: 'open' }));
  }

  function settle(id: string, result: Result) {
    const closingOdd = Number((closingOdds[id] || '').replace(',', '.'));
    setOperations((current) => current.map((operation) => operation.id === id ? { ...operation, result, closingOdd: Number.isFinite(closingOdd) && closingOdd > 1 ? closingOdd : operation.closingOdd, settledAt: result === 'open' ? undefined : new Date().toISOString(), settlementSource: result === 'open' ? undefined : 'manual' } : operation));
  }

  function changeStakeMode(mode: 'units' | 'money') {
    const current = Number(form.stake.replace(',', '.')) || 0;
    const converted = mode === 'units' ? stakeToUnits(current, unitValue) : unitsToStake(current, unitValue);
    setStakeMode(mode); setForm((value) => ({ ...value, stake: converted ? String(Number(converted.toFixed(2))) : '' }));
  }

  const settled = operations.filter((item) => item.result !== 'open'); const open = operations.filter((item) => item.result === 'open');
  const totalStake = settled.reduce((sum, item) => sum + item.stake, 0); const totalProfit = settled.reduce((sum, item) => sum + profit(item), 0);
  const wins = settled.filter((item) => item.result === 'win').length; const losses = settled.filter((item) => item.result === 'loss').length;
  const hitRate = wins + losses ? (wins / (wins + losses)) * 100 : 0; const roi = totalStake ? (totalProfit / totalStake) * 100 : 0; const currentBankroll = initialBankroll + totalProfit;
  const clvs = settled.map(operationClvPercent).filter((value): value is number => value !== null); const averageClv = clvs.length ? clvs.reduce((sum, value) => sum + value, 0) / clvs.length : 0;
  const visible = useMemo(() => operations.filter((item) => filter === 'all' || item.result === filter), [operations, filter]);
  const byLeague = useMemo(() => rankBy(operations, (item) => item.league), [operations]); const byMarket = useMemo(() => rankBy(operations, (item) => item.market), [operations]); const byOdds = useMemo(() => rankBy(operations, (item) => item.odds < 1.7 ? 'Até 1,69' : item.odds < 2 ? '1,70 a 1,99' : item.odds < 2.5 ? '2,00 a 2,49' : '2,50 ou mais'), [operations]);

  return <main className="mx-auto min-h-screen w-full max-w-7xl px-3 py-6 sm:px-5 lg:px-8">
    <header><div className="inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1 text-xs font-bold text-primary"><TrendingUp className="h-4 w-4" /> Settlement & Performance Engine</div><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Centro de Performance</h1><p className="mt-2 max-w-3xl text-muted-foreground">Controle sua banca em reais e unidades, liquide operações e acompanhe ROI, CLV e consistência.</p></header>

    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric icon={WalletCards} label="Banca atual" value={money.format(currentBankroll)} /><Metric icon={CircleDollarSign} label="Lucro acumulado" value={`${totalProfit > 0 ? '+' : ''}${money.format(totalProfit)}`} tone={totalProfit} /><Metric icon={TrendingUp} label="Lucro em unidades" value={formatUnits(stakeToUnits(totalProfit, unitValue))} tone={totalProfit} /><Metric icon={TrendingUp} label="ROI" value={`${roi > 0 ? '+' : ''}${number.format(roi)}%`} tone={roi} /><Metric icon={Clock3} label="Em aberto" value={String(open.length)} /><Metric icon={BarChart3} label="CLV médio" value={clvs.length ? `${averageClv > 0 ? '+' : ''}${number.format(averageClv)}%` : '—'} tone={averageClv} /></section>

    <section className="mt-5 rounded-2xl border bg-card p-4 sm:p-5">
      <div className="grid gap-4 lg:grid-cols-3"><label className="text-sm font-bold">Banca inicial<input type="number" min="1" value={initialBankroll} onChange={(e) => setInitialBankroll(Number(e.target.value) || 0)} className="mt-1 w-full rounded-lg border bg-background px-3 py-2" /></label><label className="text-sm font-bold">Valor de 1 unidade<input type="number" min="1" step="0.01" value={unitValue} onChange={(e) => setUnitValue(Number(e.target.value) || 0)} className="mt-1 w-full rounded-lg border bg-background px-3 py-2" /></label><div className="rounded-xl bg-muted/50 p-3 text-sm"><div className="font-bold">Conversão automática</div><div className="mt-1 text-muted-foreground">1 U = {money.format(unitValue)} · 0,50 U = {money.format(unitValue * 0.5)} · 0,25 U = {money.format(unitValue * 0.25)}</div></div></div>
    </section>

    <section className="mt-5 rounded-2xl border bg-card p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-xl font-black">Registrar operação</h2><div className="flex rounded-xl border p-1"><button type="button" onClick={() => changeStakeMode('units')} className={`rounded-lg px-3 py-1.5 text-sm font-bold ${stakeMode === 'units' ? 'bg-primary text-primary-foreground' : ''}`}>Unidades</button><button type="button" onClick={() => changeStakeMode('money')} className={`rounded-lg px-3 py-1.5 text-sm font-bold ${stakeMode === 'money' ? 'bg-primary text-primary-foreground' : ''}`}>Reais</button></div></div>
      <form onSubmit={addOperation} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-7"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className="min-h-11 rounded-xl border bg-background px-3" /><input value={form.match} onChange={(e) => setForm({ ...form, match: e.target.value })} placeholder="Jogo" className="min-h-11 rounded-xl border bg-background px-3 xl:col-span-2" /><input value={form.league} onChange={(e) => setForm({ ...form, league: e.target.value })} placeholder="Liga" className="min-h-11 rounded-xl border bg-background px-3" /><input value={form.market} onChange={(e) => setForm({ ...form, market: e.target.value })} placeholder="Mercado" className="min-h-11 rounded-xl border bg-background px-3" /><input inputMode="decimal" value={form.odds} onChange={(e) => setForm({ ...form, odds: e.target.value })} placeholder="Odd" className="min-h-11 rounded-xl border bg-background px-3" /><div><input inputMode="decimal" value={form.stake} onChange={(e) => setForm({ ...form, stake: e.target.value })} placeholder={stakeMode === 'units' ? 'Stake em U' : 'Stake R$'} className="min-h-11 w-full rounded-xl border bg-background px-3" /><div className="mt-1 text-xs text-muted-foreground">{stakeMode === 'units' ? money.format(unitsToStake(Number(form.stake.replace(',', '.')) || 0, unitValue)) : formatUnits(stakeToUnits(Number(form.stake.replace(',', '.')) || 0, unitValue))}</div></div><select value={form.result} onChange={(e) => setForm({ ...form, result: e.target.value as Result })} className="min-h-11 rounded-xl border bg-background px-3"><option value="open">Em aberto</option><option value="win">Green</option><option value="loss">Red</option><option value="push">Devolvida</option></select><button type="submit" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 font-bold text-primary-foreground"><Plus className="h-4 w-4" /> Registrar</button></form>
    </section>

    {open.length > 0 && <section className="mt-5 rounded-2xl border bg-card p-4 sm:p-5"><h2 className="text-xl font-black">Central de liquidação</h2><p className="mt-1 text-sm text-muted-foreground">Informe a odd de fechamento quando disponível.</p><div className="mt-4 space-y-3">{open.map((item) => <div key={item.id} className="grid gap-3 rounded-2xl border p-4 lg:grid-cols-[1fr_150px_auto]"><div><div className="font-black">{item.match}</div><div className="text-sm text-muted-foreground">{item.market} · odd {number.format(item.odds)} · {formatUnits(stakeToUnits(item.stake, unitValue))} ({money.format(item.stake)})</div></div><input inputMode="decimal" value={closingOdds[item.id] || ''} onChange={(e) => setClosingOdds((current) => ({ ...current, [item.id]: e.target.value }))} placeholder="Odd fechamento" className="min-h-11 rounded-xl border bg-background px-3" /><div className="flex flex-wrap gap-2"><SettleButton label="Green" icon={Check} onClick={() => settle(item.id, 'win')} /><SettleButton label="Red" icon={X} onClick={() => settle(item.id, 'loss')} danger /><SettleButton label="Devolvida" icon={RotateCcw} onClick={() => settle(item.id, 'push')} /></div></div>)}</div></section>}

    <section className="mt-5 grid gap-5 lg:grid-cols-3"><Ranking title="Desempenho por liga" rows={byLeague} /><Ranking title="Desempenho por mercado" rows={byMarket} /><Ranking title="Desempenho por odds" rows={byOdds} /></section>

    <section className="mt-5 rounded-2xl border bg-card p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-xl font-black">Histórico auditável</h2><select value={filter} onChange={(e) => setFilter(e.target.value)} className="min-h-10 rounded-xl border bg-background px-3 font-semibold"><option value="all">Todos</option><option value="open">Em aberto</option><option value="win">Greens</option><option value="loss">Reds</option><option value="push">Devolvidas</option></select></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1150px] text-sm"><thead className="text-left text-muted-foreground"><tr className="border-b"><th className="p-3">Data</th><th className="p-3">Jogo</th><th className="p-3">Mercado</th><th className="p-3">Odd</th><th className="p-3">Unidades</th><th className="p-3">Stake</th><th className="p-3">CLV</th><th className="p-3">Resultado</th><th className="p-3">P/L</th><th className="p-3"></th></tr></thead><tbody>{visible.map((item) => { const clv = operationClvPercent(item); return <tr key={item.id} className="border-b last:border-0"><td className="p-3">{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className="p-3 font-bold">{item.match}</td><td className="p-3">{item.market}</td><td className="p-3">{number.format(item.odds)}</td><td className="p-3 font-bold">{formatUnits(stakeToUnits(item.stake, unitValue))}</td><td className="p-3">{money.format(item.stake)}</td><td className={`p-3 font-black ${clv != null && clv > 0 ? 'text-emerald-500' : clv != null && clv < 0 ? 'text-red-500' : ''}`}>{clv == null ? '—' : `${clv > 0 ? '+' : ''}${number.format(clv)}%`}</td><td className="p-3"><ResultBadge result={item.result} onChange={(result) => settle(item.id, result)} /></td><td className={`p-3 font-black ${profit(item) > 0 ? 'text-emerald-500' : profit(item) < 0 ? 'text-red-500' : ''}`}>{formatUnits(stakeToUnits(profit(item), unitValue))}<div className="text-xs font-normal">{money.format(profit(item))}</div></td><td className="p-3"><button aria-label="Excluir operação" onClick={() => setOperations((current) => current.filter((operation) => operation.id !== item.id))} className="rounded-lg border p-2 text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></button></td></tr>; })}</tbody></table></div>{visible.length === 0 && <div className="mt-4 rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhuma operação encontrada.</div>}</section>
  </main>;
}

function rankBy(items: Operation[], keyOf: (item: Operation) => string) { const map = new Map<string, { name: string; settled: number; stake: number; profit: number; wins: number; losses: number }>(); items.filter((item) => item.result !== 'open').forEach((item) => { const key = keyOf(item) || 'Não informado'; const row = map.get(key) || { name: key, settled: 0, stake: 0, profit: 0, wins: 0, losses: 0 }; row.settled += 1; row.stake += item.stake; row.profit += profit(item); if (item.result === 'win') row.wins += 1; if (item.result === 'loss') row.losses += 1; map.set(key, row); }); return [...map.values()].map((row) => ({ ...row, roi: row.stake ? row.profit / row.stake * 100 : 0 })).sort((a, b) => b.roi - a.roi).slice(0, 5); }
function Metric({ icon: Icon, label, value, tone = 0 }: { icon: typeof Target; label: string; value: string; tone?: number }) { return <div className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2 text-xs font-semibold text-muted-foreground"><Icon className="h-4 w-4 text-primary" />{label}</div><div className={`mt-2 text-2xl font-black ${tone > 0 ? 'text-emerald-500' : tone < 0 ? 'text-red-500' : ''}`}>{value}</div></div>; }
function Ranking({ title, rows }: { title: string; rows: ReturnType<typeof rankBy> }) { return <div className="rounded-2xl border bg-card p-4"><h2 className="font-black">{title}</h2><div className="mt-3 space-y-2">{rows.map((row, index) => <div key={row.name} className="rounded-xl bg-muted/40 p-3"><div className="flex items-center justify-between gap-3"><span className="truncate font-bold">#{index + 1} {row.name}</span><span className={`font-black ${row.roi > 0 ? 'text-emerald-500' : row.roi < 0 ? 'text-red-500' : ''}`}>{row.roi > 0 ? '+' : ''}{number.format(row.roi)}%</span></div><div className="mt-1 text-xs text-muted-foreground">{row.settled} operações · {row.wins}G · {row.losses}R · {money.format(row.profit)}</div></div>)}{rows.length === 0 && <p className="text-sm text-muted-foreground">Aguardando operações liquidadas.</p>}</div></div>; }
function ResultBadge({ result, onChange }: { result: Result; onChange: (result: Result) => void }) { return <select aria-label="Resultado da operação" value={result} onChange={(e) => onChange(e.target.value as Result)} className="rounded-lg border bg-background px-2 py-1 text-xs font-bold"><option value="open">Em aberto</option><option value="win">Green</option><option value="loss">Red</option><option value="push">Devolvida</option></select>; }
function SettleButton({ label, icon: Icon, onClick, danger = false }: { label: string; icon: typeof Check; onClick: () => void; danger?: boolean }) { return <button type="button" onClick={onClick} className={`inline-flex min-h-10 items-center gap-1.5 rounded-xl border px-3 text-sm font-bold ${danger ? 'border-red-500/40 text-red-500' : ''}`}><Icon className="h-4 w-4" />{label}</button>; }
