'use client';

import { useEffect, useMemo, useState } from 'react';
import LiveHistoryPageBase from './LiveHistoryPageBase';

type CatalogMatch = { id:number; minute:number|string; competition:string; homeTeam:{name:string;score:number}; awayTeam:{name:string;score:number} };

const FOLLOW_KEY='ia-cantos-followed-live-v1';
function readFollowedIds(){try{const parsed=JSON.parse(window.localStorage.getItem(FOLLOW_KEY)??'[]');return Array.isArray(parsed)?parsed.map(Number).filter(value=>Number.isFinite(value)&&value>0).slice(0,12):[];}catch{return[];}}
function writeFollowedIds(ids:number[]){window.localStorage.setItem(FOLLOW_KEY,JSON.stringify([...new Set(ids)].slice(0,12)));}
function textKey(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}

export default function LiveHistoryPage(){
 const[pageGeneration,setPageGeneration]=useState(0);const[catalog,setCatalog]=useState<CatalogMatch[]>([]),[catalogSearch,setCatalogSearch]=useState(''),[catalogError,setCatalogError]=useState<string|null>(null),[followedIds,setFollowedIds]=useState<number[]>([]);
 useEffect(()=>{const initialFollowed=readFollowedIds();setFollowedIds(initialFollowed);},[]);
 useEffect(()=>{let cancelled=false,pending=false;const loadCatalog=async()=>{if(document.visibilityState!=='visible'||pending)return;pending=true;try{const response=await fetch(`/api/live/catalog?t=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(10_000)});const data=await response.json() as{matches?:CatalogMatch[];error?:string};if(!response.ok)throw new Error(data.error??'Falha ao carregar jogos ao vivo');if(cancelled)return;const matches=Array.isArray(data.matches)?data.matches:[];setCatalog(matches);setCatalogError(null);}catch(error){if(!cancelled)setCatalogError(error instanceof Error?error.message:'Falha ao carregar catálogo');}finally{pending=false;}};void loadCatalog();const timer=window.setInterval(()=>void loadCatalog(),45_000);const onVisibilityChange=()=>{if(document.visibilityState==='visible')void loadCatalog();};document.addEventListener('visibilitychange',onVisibilityChange);return()=>{cancelled=true;window.clearInterval(timer);document.removeEventListener('visibilitychange',onVisibilityChange);};},[]);
 const catalogResults=useMemo(()=>{const query=textKey(catalogSearch.trim());if(!query)return[];return catalog.filter(match=>textKey(`${match.homeTeam.name} ${match.awayTeam.name} ${match.competition}`).includes(query)).slice(0,20);},[catalog,catalogSearch]);
 const toggleFollow=(id:number)=>{const current=readFollowedIds();const next=current.includes(id)?current.filter(value=>value!==id):[id,...current].slice(0,12);writeFollowedIds(next);setFollowedIds(next);setPageGeneration(value=>value+1);};

 return <><section className="mx-auto mt-6 w-full max-w-7xl px-4 md:px-8"><div className="rounded-2xl border border-border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-bold">Encontrar qualquer jogo ao vivo</h2><p className="text-xs text-muted-foreground">{catalog.length} partida(s) disponíveis · {followedIds.length} escolhida(s) para acompanhamento prioritário</p></div></div><input value={catalogSearch} onChange={event=>setCatalogSearch(event.target.value)} placeholder="Buscar time ou competição entre todos os jogos ao vivo..." className="mt-3 w-full rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none focus:border-emerald-500" />{catalogError&&<p className="mt-2 text-xs text-red-300">{catalogError}</p>}{catalogSearch&&<div className="mt-3 max-h-80 space-y-2 overflow-auto">{catalogResults.map(match=>{const followed=followedIds.includes(match.id);return <div key={match.id} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-background/40 p-3"><div className="min-w-0"><p className="truncate text-xs text-muted-foreground">{match.competition} · {match.minute}&apos;</p><p className="truncate font-semibold">{match.homeTeam.name} x {match.awayTeam.name}</p><p className="text-xs text-muted-foreground">{match.homeTeam.score}–{match.awayTeam.score}</p></div><button type="button" onClick={()=>toggleFollow(match.id)} className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-bold ${followed?'border-emerald-500 bg-emerald-500/15 text-emerald-300':'border-border hover:bg-muted'}`}>{followed?'Acompanhando':'Acompanhar'}</button></div>;})}{catalogResults.length===0&&<p className="rounded-xl border border-dashed border-border p-3 text-sm text-muted-foreground">Nenhuma partida encontrada nessa busca.</p>}</div>}</div></section><LiveHistoryPageBase key={pageGeneration} followedIds={followedIds}/></>;
}
